### ISSUE TITLE
recursion bug with global glossary

### ISSUE THREAD

**Issue by bdarcus** [tecosaur/org-glossary#1]
I ran into this again, and unfortunately, lost the backtrace the one time I could get one, and can't re-generate it. I will update this post when and if I can get more info.

------------

What I do remember of the backtrace:

Org-glossary gets pretty far in the process (I believe of parsing the file), and IIRC the last function before it freezes was `org-strip-quotes`.

And the error is a "max depth exceeded" one; which I guess signals an infinite recursion bug.

This happened when I was just doing a generic latex export; e.g I can't export unless I comment out `org-glossary-global-terms`.

**Comment by bdarcus** [comment]
I updated just now, and now can't reproduce this error, so will close this!

**Comment by tecosaur** [comment]
Great! I'm happy to hear that :slightly_smiling_face:
