### ISSUE TITLE
No links in html or odt export

### ISSUE THREAD

**Issue by anthrolisp** [tecosaur/org-glossary#10]
There are no links in html or odt export but M-x org-glossary-mode works. I am using Ubuntu.

**Comment by tecosaur** [comment]
I just tried an HTML export with the example from https://github.com/tecosaur/org-glossary/issues/9#issuecomment-1359675722, and it appears to work fine.

Please provide a MWE and detailed reproduction steps including the Emacs and Org version you are using.

**Comment by authsec** [comment]
I can confirm HTML export to be working with that example. The export also works when using the external glosses with `#+glossary_sources`

<img width="945" alt="Screenshot 2023-01-31 at 22 43 55" src="https://user-images.githubusercontent.com/7973409/215890947-1d36afb5-c087-4e23-8cc6-4628a267de2f.png">

**Comment by tecosaur** [comment]
Thanks. ODT falls back to the general export setup (see below), but I'm glad to hear it works decently. I'll close the issue then.

https://github.com/tecosaur/org-glossary/blob/8ac176c068fbbcc44a9c3859e8ee04b03038a73e/org-glossary.el#L154-L174
