### ISSUE TITLE
Acronyms at first use but no acronyms list/heading

### ISSUE THREAD

**Issue by jdm204** [tecosaur/org-glossary#13]
I couldn't find a way in the documentation to process acronyms (produce the expanded form at first use on export) but not export and link the actual definition list of acronyms in the exported document (on a per-document basis).

I've tried

```
* Acronyms :noexport:
```
(with that tag in `org-export-exclude-tags`) but no luck.

Something very close is

```
#+print_glossary: :type nil
```

but then the acronyms hyperlink to where the printed acronym list *would have been in the document*, i.e where the `#+print_glossary` statement is put, which makes it seem to the reader they are linking to random unrelated text.

What would be great is if we could have the first-use expansion but no links, just by using an excluded tag like `:noexport:`!

**Comment by tecosaur** [comment]
Hmm, you could create a new acronym-like category which just doesn't produce a glossary section.

```emacs-lisp
(add-to-list 'org-glossary-headings '("Acronym sans link" . acronym-nolink))

(org-glossary-set-export-spec t 'acronym-nolink
  :heading ""
  :use "%v"
  :first-use "%v (%u)"
  :definition-structure "")
```

This is untested, but it should be a decent starting point.
