### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by Ypot** [tecosaur/org-glossary#14]
This link is not working:

> For more details on how this works, see [Structure of an export template set](https://github.com/tecosaur/org-glossary/blob/master/Structure%20of%20an%20export%20template%20set).

Source:
https://github.com/tecosaur/org-glossary/blob/master/org-glossary.org

**Comment by tecosaur** [comment]
This is just an issue with GitHub's Org renderer.

**Comment by Ypot** [comment]
https://github.com/tecosaur/org-glossary/blob/master/Structure%20of%20an%20export%20template%20set
