### ISSUE TITLE
Suggestion: Headlines

### ISSUE THREAD

**Issue by Ypot** [tecosaur/org-glossary#15]
`In addition terms in headings are ignored, as this is considered broadly desirable.`

Could it be a customizable variable?

**Comment by tecosaur** [comment]
Sure, how about this?

```lisp
(defcustom org-glossary-skip-automatic-in-headings t
  "Don't detect plain uses of terms in headings."
  :type 'boolean)
```

**Comment by Ypot** [comment]
Lovely!

**Comment by tecosaur** [comment]
I honestly don't know why it's taken so long :sweat_smile: but `org-glossary-autodetect-in-headings` now exists as of 1438718e7e2fc3a13c0b3ad1200b1f1e622c212d.
