### ISSUE TITLE
Ref'ing an external source with org-glossary-global-terms generates wrong-type-argument stringp nil

### ISSUE THREAD

**Issue by RDeYoung** [tecosaur/org-glossary#18]
What happened:
Created separate .org file containing list of terms and their defs.

Debugger output:
org-glossary--maybe-add-extra-terms(org-glossary--get-terms-cached nil t ((:file "/Users/Richard.Deyoung/Documents/GTD/Roam/20220809111548-projects.org.gpg" :location nil :only-contents nil :line nil :env nil :minlevel nil)))
  org-glossary--get-terms-cached()
  org-glossary-update-terms()
  org-glossary-mode()
  run-hooks(change-major-mode-after-body-hook text-mode-hook outline-mode-hook org-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook text-mode-hook outline-mode-hook org-mode-hook))
  run-mode-hooks(org-mode-hook)
  org-mode()
  org-mode-restart()
  org-ctrl-c-ctrl-c(nil)
  funcall-interactively(org-ctrl-c-ctrl-c nil)
  command-execute(org-ctrl-c-ctrl-c)

Org-glossary config:
(use-package org-glossary
  :hook (org-mode . org-glossary-mode)
  :custom
  (setq org-glossary-global-terms "20240208142351-glossaries.org")
  (setq org-glossary-toplevel-only 'nil)
  )

Emacs version:
GNU Emacs 28.2 (build 2, x86_64-apple-darwin22.3.0, NS appkit-2299.40 Version 13.2.1 (Build 22D68)) of 2023-10-31

Package versions:
Org mode version 9.6.15 9.6.15-??-478b40d
Org-glossary commit 22b76daf4fd261f4cd6fc07d3038f4179722608c

OS:
ProductName:            macOS
ProductVersion:         13.2.1
BuildVersion:           22D68

**Comment by RDeYoung** [comment]
No response

**Comment by tecosaur** [comment]
Apologies for not responding sooner, I've developed quite the backlog in my projects.

Just using an external definition file I can't reproduce the error. Might you have a MWE I can try?

**Comment by RDeYoung** [comment]
No worries!
Was fiddling with my configs right after my previous comment and got it working.

Could've been a result of a "doom sync -u" and restarting Doom.

Anyways, it's all good and I appreciate you getting back to me.

I work in Information Security and LOVE this package.

Comes in VERY handy with all of the InfoSec definitions, acronyms, and glossaries!!

Take care
