### ISSUE TITLE
README: Provide a screenshot of the example export?

### ISSUE THREAD

**Issue by yantar92** [tecosaur/org-glossary#2]
It would be nice if the example were also accompanied with the corresponding export output.

**Comment by tecosaur** [comment]
The main blocker with this is coming up with a good idea of how to effectively display as many of the key features as possible in one image.

**Comment by yantar92** [comment]
screencast maybe?

**Comment by jdm204** [comment]
It's subjective, but for me, even something as simple as

![org-glossary](https://user-images.githubusercontent.com/34479575/221863446-a062d520-44b2-439c-b376-84218848c982.png)

(mirroring the readme example) would help to illustrate the basic idea.

**Comment by tecosaur** [comment]
Hmm, I suppose I could use the README example. Perhaps something like

![image](https://user-images.githubusercontent.com/20903656/221874249-2f2dd164-5a12-41ad-907c-cbac13211b11.png)

**Comment by jdm204** [comment]
I think that's good---in seconds you can see what the package does, and also shows off the in-buffer highlighting.

(Lovely sans and serif fonts btw, I've stolen both from your config, thanks.)

**Comment by tecosaur** [comment]
Well, I guess it's better than nothing. Added.
