### ISSUE TITLE
Org mode minimal version

### ISSUE THREAD

**Issue by fleimgruber** [tecosaur/org-glossary#3]
Just curious: What is the reason this needs org >=9.6? I am using org from ELPA so stuck on 9.5 there, but would love to have this functionality.

**Comment by yantar92** [comment]
AFAIK, mostly because this is a package aiming to be included into the core. Though I am 90% sure that it should work with older Org. You can try it by loading org-glossary manually.

**Comment by fleimgruber** [comment]
Thanks for your thoughts. I loaded it manually for now.

**Comment by tecosaur** [comment]
I was thinking of using a refactoring of `org-export-expand-include-keyword` that I haven't yet pushed to Org in this package, but ended up duplicating code instead. This could probably be safely bumped down if I never actually get around to that.

**Comment by fleimgruber** [comment]
I see. In that case I guess the best thing to do is whatever makes your development easier/faster. Solved for me, feel free to close.
